CREATE TABLE if NOT EXISTS Cats (`id` INT NOT NULL AUTO_INCREMENT , PRIMARY KEY (`id`));
ALTER TABLE Cats ADD name VARCHAR(256) NULL COMMENT '{{0}}';
ALTER TABLE Cats ADD counter INT(255) NULL COMMENT '{{1}}';
ALTER TABLE Cats ADD description TEXT(100) NULL COMMENT '{{2}}';