ALTER TABLE `User` CHANGE `name` `name` VARCHAR(150) NULL COMMENT '{{0}}';
ALTER TABLE `User` CHANGE `password` `password` VARCHAR(150) NULL COMMENT '{{1}}';
ALTER TABLE `User` CHANGE `email` `email` VARCHAR(150) NULL COMMENT '{{2}}';
ALTER TABLE `User` CHANGE `role` `role` VARCHAR(100) NULL COMMENT '{{3}}';
ALTER TABLE User ADD salt VARCHAR(200) NULL COMMENT '{{4}}';