CREATE TABLE if NOT EXISTS User (`id` INT NOT NULL AUTO_INCREMENT , PRIMARY KEY (`id`));
ALTER TABLE User ADD name VARCHAR(150) NULL COMMENT '{{0}}';
ALTER TABLE User ADD password VARCHAR(150) NULL COMMENT '{{1}}';
ALTER TABLE User ADD email VARCHAR(150) NULL COMMENT '{{2}}';
ALTER TABLE User ADD roles JSON NULL COMMENT '{{3}}';
ALTER TABLE User ADD salt VARCHAR(200) NULL COMMENT '{{4}}';